apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-sa
  namespace: ai-ops
---
# O Archivist precisa de menos permiss√£o, apenas para salvar dados
apiVersion: v1
kind: ServiceAccount
metadata:
  name: archivist-sa
  namespace: ai-ops
---
# ClusterRole: Define o que um Auditor pode fazer (Ler tudo, Alterar nada)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-auditor-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "events", "nodes", "namespaces", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding: Vincula a identidade do Watcher ao papel de Auditor
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher-auditor-binding
subjects:
- kind: ServiceAccount
  name: watcher-sa
  namespace: ai-ops
roleRef:
  kind: ClusterRole
  name: agent-auditor-role
  apiGroup: rbac.authorization.k8s.io
