apiVersion: v1
kind: Service
metadata:
  name: alerting-test-app
  namespace: app-production
  labels:
    monitor: "true"
spec:
  selector:
    app: crash-app
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
