apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-test-app
  namespace: app-production
  labels:
    monitor: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-app
  template:
    metadata:
      labels:
        app: crash-app
        monitor: "true"
    spec:
      containers:
      - name: main
        image: busybox
        command: ["sh", "-c", "sleep 5 && exit 1"]
