apiVersion: v1
kind: Namespace
metadata:
  name: ai-ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: communication
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-production
