apiVersion: v1
kind: Service
metadata:
  name: oom-stress-test
  namespace: app-production
  labels:
    monitor: "true"
spec:
  selector:
    app: oom-stress
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
